modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"

[[mods]]
modId="runicstructures"
version="${mod_version}"
displayName="Runic Structures"
authors="Otectus"
description='''
Forces hostile mob spawns inside selected structures as if light level is 0, regardless of time or light.
Structures become permanent mob hotbeds — tuned for the Runecraft modpack ecosystem with deep integration defaults.
'''

[[dependencies.runicstructures]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.runicstructures]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
